apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cache implementation
- implementations/squid

# Common resources (shared across all implementations)
- service.yaml

commonLabels:
  component: multimedia-downloader

