apiVersion: v1
kind: Service
metadata:
  name: multimedia-downloader
  labels:
    app: multimedia-downloader
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3128
    protocol: TCP
    name: http-proxy
  selector:
    app: multimedia-downloader
    component: multimedia-downloader

