apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${EPP_NAME}-binding
subjects:
- kind: ServiceAccount
  name: ${EPP_NAME}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: epp-reader
