apiVersion: v1
kind: PersistentVolume
metadata:
  name: ec-cache-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /tmp/vllm-ec-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ec-cache-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-sim-encoder
  labels:
    app: qwen3-vl-2b-epd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-vl-2b-epd
  template:
    metadata:
      labels:
        app: qwen3-vl-2b-epd
        llm-d.ai/role: encode
    spec:
      containers:
      - name: vllm
        image: ghcr.io/revit13/vllm-cpu-env:latest
        imagePullPolicy: IfNotPresent
        args:
        - "--model=Qwen/Qwen3-VL-2B-Instruct"
        - "--port=8000"
        - "--data-parallel-size=1"
        - "--no-enable-prefix-caching"
        - "--mm-encoder-only"
        - "--ec-transfer-config"
        - '{"ec_connector": "ECExampleConnector", "ec_role": "ec_producer", "ec_connector_extra_config": {"shared_storage_path": "/shared-ec-cache"}}'
        ports:
        - name: encode-http
          containerPort: 8000
          protocol: TCP
        - name: encode-rank1
          containerPort: 8001
          protocol: TCP
        - name: encode-rank2
          containerPort: 8002
          protocol: TCP
        - name: encode-rank3
          containerPort: 8003
          protocol: TCP
        - name: encode-rank4
          containerPort: 8004
          protocol: TCP
        - name: encode-rank5
          containerPort: 8005
          protocol: TCP
        - name: encode-rank6
          containerPort: 8006
          protocol: TCP
        - name: encode-rank7
          containerPort: 8007
          protocol: TCP
        env:
        - name: PORT
          value: "8000"
        - name: HTTP_PROXY
          value: "http://multimedia-downloader.default.svc.cluster.local:80"
        - name: HTTPS_PROXY
          value: "http://multimedia-downloader.default.svc.cluster.local:80"
        - name: NO_PROXY
          value: "localhost,127.0.0.1,.svc.cluster.local"
        volumeMounts:
        - name: uds-socket
          mountPath: /tmp/tokenizer
        - mountPath: /shared-ec-cache
          name: ec-cache
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: uds-socket
        emptyDir: {}
      - name: ec-cache
        persistentVolumeClaim:
          claimName: ec-cache-pvc
